### PR TITLE
Update install-unifi.sh

### PR DESCRIPTION
**Pull request by ReinaldoFeitosa**
Force update snappyjava when openjdk8 is update. Solve problem adopt/disconect in version 5.5.20

### CODE REVIEW

**Comment by ssbarnea** [comment]
@ReinaldoFeitosa How about updating the branch?

**Comment by ReinaldoFeitosa** [comment]
How to resolved conflicts?

**Comment by ReinaldoFeitosa** [comment]
because my pullrequest was not accepted?

**Comment by ssbarnea** [comment]
@ReinaldoFeitosa Usually you do a pull from upstream/master to your branch, solve conflicts locally, push to your fork/branch. GitHub will detect that your fork was updated and will refresh the PR,the conflict will go away.

Be sure that your fork is in sync with upstream (this repo).

**Comment by gozoinks** [comment]
Is it necessary to delete (and thereby reinstall) snappyjava now that we're force installing everything?

**Comment by ReinaldoFeitosa** [comment]
Yes, but you need to download all unnecessary packages.
If java is updated you need to reinstall snappyjava

**Pull request closed without merging**
