### PR TITLE
Update Unifi and package versions

### PR DESCRIPTION
**Pull request by jmcphail**

### CODE REVIEW

**Comment by andrewpurkett** [comment]
@jmcphail thank you!

**Comment by kklouzal** [comment]
Thank you for the continued support, any progress on getting this package into the pfSense source tree so we can update easily from the package browser?

**Comment by jmcphail** [comment]
@kklouzal its something I believe that the original package maintainer @gozoinks envisioned, and I have looked into it briefly.  Before this happens, we need to fix the package dependency installation (having to manually update the list is not a long-term solution), which I have made some progress on.

**Comment by oneguynick** [comment]
Beat me to the punch 👍  This patch worked great on my pfsense 2.3.2 build

**Comment by gozoinks** [comment]
Yes, the dependencies and the proprietary binary are the obstacles. Automating these inclusions in a reliable, maintainable, and compliant way is the challenge. 

Nevertheless, if someone were inclined to put together a test repository and a framework for a package, we could be a little further along when we come back to these details.

**Comment by KeiroD** [comment]
>test repository

You can do that by creating a new branch and PRing the current code from main repository to dev repository...

**Pull request merged**
