### PR TITLE
Update package versions and Unifi v5.4.11

### PR DESCRIPTION
**Pull request by jmcphail**

### CODE REVIEW

**Comment by jmcphail** [comment]
Am working on a recursive function that will eventually remove the requirement to preinstall named main package dependencies.

**Comment by gozoinks** [comment]
Exciting! Big changes. 

With the new mechanism and the new external script, I'm inclined to let this soak just a bit before merging. Any reservations about relying on json.sh?

**Comment by gozoinks** [comment]
We should also make sure the snappyjava dance we do at the end won't break if the version and path change

**Comment by jmcphail** [comment]
Letting it soak for a bit is a good idea.  I may be able to remove the reliance on the JSON.sh with some better regex-fu, but it is convenient.  I don't know if the snappyjava thing is still required.  I believe it was a work-around for AP adoption, maybe its been fixed and we don't need it anymore.  I have some hardware and time next week, I can try a real world test.  Closing this for now.

**Pull request closed without merging**
