### PR TITLE
Update install-unifi.sh

### PR DESCRIPTION
**Pull request by shahil2013**

### CODE REVIEW

**Review by gnkidwell — CHANGES_REQUESTED** [review]
@shahil2013 FYI there is already a pull request created for this...

**Comment by gnkidwell** [comment]
> _No description provided._

I have made a new pull request under #211 , this is the newest Official Release from Ubiquiti. Also, the current patch that you have made for 6.0.23 does not fix dependency errors. My pulls do, just an FYI.

**Review by gnkidwell — CHANGES_REQUESTED** [review]
This has already been uploaded, also 6.0.28 is on #211

**Comment by jmbwell** [comment]
Thank you!

**Pull request closed without merging**
