### PR TITLE
updated to 6.0.28

### PR DESCRIPTION
**Pull request by EasyAsABC123**
Tested on 
```
2.4.5-RELEASE-p1 (amd64)
built on Tue Jun 02 17:51:17 EDT 2020
FreeBSD 11.3-STABLE
--
```

### CODE REVIEW

**Comment by gnkidwell** [comment]
There is already a pull request for this under #211

**Comment by EasyAsABC123** [comment]
@gnkidwell you bumped python to `python27` which didn't seem necessary

**Comment by gnkidwell** [comment]
> @gnkidwell you bumped python to `python27` which didn't seem necessary

You mean python37 to 27... It is a dependency issue... It cleans up the entire shell script.. But to each their own... Python37 had to be installed for a dependency for another pkg... That was the whole purpose behind that... I also fixed all of the dependency errors by reordering everything so it installs clean on a new system...

**Comment by EasyAsABC123** [comment]
@gnkidwell ah, cool.  That wasn't in your PR when i read through it so i assumed it was by mistake ;) good work

**Pull request closed without merging**
