### PR TITLE
Update install-unifi.sh

### PR DESCRIPTION
**Pull request by Jarv1s92**
Latest version of the unifi controller - URL change

### CODE REVIEW

**Comment by ReinaldoFeitosa** [comment]
Tested update e install
Approved!

**Comment by jmbwell** [comment]
Can’t merge while the PR is a draft…

**Comment by ReinaldoFeitosa** [comment]
> Latest version of the unifi controller - URL change

Update PR to Open

**Comment by dannyeuu** [comment]
There is #157 with a more updated version!

**Comment by drd3rp** [comment]
wanting to move this into a docker img

**Comment by jmbwell** [comment]
Superseded

**Pull request closed without merging**
