### PR TITLE
Update unifi controller to 5.13.32

### PR DESCRIPTION
**Pull request by ReinaldoFeitosa**

### CODE REVIEW

**Comment by grayhatteralerts** [comment]
Hi don't use git hub much and I am script kiddy at best, so my apologies for not understanding but how do I go ahead and get the script that you propose being committed?  I would like to try it and update to 5.13.32. .

**Comment by grayhatteralerts** [comment]
NM, thank you,  I just recreated the script locally and ran it.  Seems to working well.

**Comment by tong2x** [comment]
@grayhatteralerts
could you provide instruction how to run edit and locally?

**Comment by grayhatteralerts** [comment]
> @grayhatteralerts
> could you provide instruction how to run edit and locally?

@tong2x I downloaded the original code and open it an editor like sublime, then I looked for this line "UNIFI_SOFTWARE_URL="http://dl.ubnt.com/unifi/5.13.29/UniFi.unix.zip"  and replaced it with "UNIFI_SOFTWARE_URL="http://dl.ubnt.com/unifi/5.13.32/UniFi.unix.zip"  I then saved the new script a looked up how to move the script to the pfsense box via ssh, once its on there I just ran it the same way the original instructions tell you to.

**Comment by tong2x** [comment]
tested also, working ok
opnsense 20.7
upgrade from 29 to 32

**Pull request merged**
