### PR TITLE
Update to Unifi 5 and pfSense 2.3

### PR DESCRIPTION
**Pull request by jmcphail**
Updates Unifi to 5.0.6 and installs FreeBSD packages latest 10.3 release.

Also replace snappyjava version.

### CODE REVIEW

**Comment by jmcphail** [comment]
This is obviously a nightmare to maintain.  Working on a way to track versions and deps of mongodb, openjdk, etc.

The file packagesite.yaml in the archive http://pkg.freebsd.org/freebsd:10:x86:64/latest/packagesite.txz has the information we need to track automatically.

My shell script-fu is rusty.

**Comment by jmcphail** [comment]
I found a JSON shell parser that seems to work on the packagesite.yaml file.
https://github.com/dominictarr/JSON.sh

`[2.3.1-RELEASE][root@mypfvm.localdomain]/root: grep '"name":"mongodb"' packagesite.yaml | ./JSON.sh -l | pcregrep -o1 -o2 --om-separator=- '^\["deps"\,"(.*)","version"\]\s+"(.*)"$'`

Produces the following dependency list for mongodb:
`snappy-1.1.3`
`v8-3.18.5_1`
`pcre-8.38_1`

Getting closer...

**Comment by gozoinks** [comment]
You're doing noble work. This kind of maintenance challenge has had me thinking about whether and how to keep the project moving (which has meant it has not been moving).

Do you anticipate further changes or should I go ahead and test this?

**Comment by jmcphail** [comment]
Thanks for the feedback and testing.  I agree with you... whether or not to continue with this project.  I think the package dependency tracking is very doable.

More changes are coming...  which will get us to hopefully dealing with #11 and #12 eventually.

**Pull request merged**
